### ISSUE TITLE
Importation scope/test speed

### ISSUE THREAD

**Issue by THB-account** [THB-account/Julia4ML_GA#20]
Please  just import the functions needed for tests instead of "using" the whole library. For example change
"""
using Random                                 ==>    using Random:default_rng()

rng = Random.default_rng()             ==>   rng = default_rng()
....

"""

**Comment by benbaute** [comment]
Or may be just use the actual import function instead?

import Random
rng = Random.default_rng() 

(rng = default.rng throws not defined error)

**Comment by THB-account** [comment]
While it seems to make no performance difference writing "using Module:function" it reduces the amount of names introduced to the namespace. Therefore for testing it actually seems as of now not required to make this change (but for writing a package it should be done). 

"(rng = default.rng throws not defined error)" probably means "default_rng()". For this you have to use "using Random:default_rng".
I made a typo in the first comment, should be "using Random:default_rng".
