### ISSUE TITLE
Problem while running pluto notebook

### ISSUE THREAD

**Issue by Omadzze** [THB-account/Julia4ML_GA#34]
Failed to show value:

could not load library "libGR.dll"

The specified module could not be found.

Stack trace
Here is what happened, the most recent locations are first:

setcharheight(height::Float64) @ GR.jl:1395
gr_set_font(f::Plots.Font, s::Plots.Subplot{Plots.GRBackend}; halign::Symbol, valign::Symbol, color::ColorTypes.RGB{FixedPointNumbers.N0f8}, rotation::Int64) @ gr.jl:390
_update_min_padding!(sp::Plots.Subplot{Plots.GRBackend}) @ gr.jl:767
Base @ generator.jl:47
_collect(c::Matrix{RecipesBase.AbstractLayout}, itr::Base.Generator{Matrix{RecipesBase.AbstractLayout}, typeof(Plots._update_min_padding!)}, ::Base.EltypeUnknown, isz::Base.HasShape{2}) @ [array.jl:854](https://github.com/JuliaLang/julia/tree/3120989f39bb7ef7863c4aab8ab1227cf71eec66/base/array.jl#L851)
Base @ array.jl:763
Base @ abstractarray.jl:3282
_update_min_padding!(layout::Plots.GridLayout) @ layouts.jl:282
prepare_output(plt::Plots.Plot{Plots.GRBackend}) @ plot.jl:189
show(io::IOContext{IOBuffer}, m::MIME{Symbol("image/svg+xml")}, plt::Plots.Plot{Plots.GRBackend}) @ output.jl:214

**Comment by anjailg** [comment]
not reproducable
