### ISSUE TITLE
Remove """ as in selection.md for example

### ISSUE THREAD

**Issue by jherzog99** [THB-account/Julia4ML_GA#36]
I think you can just use
````@docs
    selection_function(fitness, selection_number, rng)

Implements a selection function.
...
...
```

or I think there is a possibility to refer to your docstring in the original code and you don't have to write it twice (like in crossover.md)

**Comment by anjailg** [comment]
Docstrings are hard copied instead of automatically posted there again via the auto docs functions

**Comment by benbaute** [comment]
This is not an issue. This function is not in the code. It is just a template to show how the selection, crossover and mutation function can be implemented.
