### ISSUE TITLE
Feedback before presentations

### ISSUE THREAD

**Issue by adrhill** [THB-account/Julia4ML_GA#39]
Hi all,

here's some quick feedback before the presentations in two weeks.
I'm opening this as a single issue to not spam your repository.

### Documentation
* Please add a disclaimer to the README that your repository is part of course work at TU Berlin
* Fantastic job on the documentation. I love that you broke it up into several smaller pages and manually included the relevant functions!
* Maybe you could visualize the optimization by plotting a fitness function and different generations of optimization?
* This looks a bit odd, just write `fitness_function(x) = (1-x[1])^2 + 100*(x[2]-x[1]^2)^2`
https://github.com/THB-account/Julia4ML_GA/blob/1488fce07610da3bf5d159e77c945b94afef66fb/docs/src/index.md?plain=1#L34

### Code
* It might be desirable to run the optimizer in lower precision, e.g. `Float32` by adding a type parameter instead of hard-coding `Float64`
https://github.com/THB-account/Julia4ML_GA/blob/1488fce07610da3bf5d159e77c945b94afef66fb/src/ga.jl#L25-L32
* This is a matter of taste, but since the types`A` and `R` aren't used anywhere in your method, you could also just write `mutation!(population::AbstractArray, ga::GeneticAlgorithm, rng::AbstractRNG)`
https://github.com/THB-account/Julia4ML_GA/blob/1488fce07610da3bf5d159e77c945b94afef66fb/src/ga.jl#L183-L189
* You can use `f::Function=identity` here
https://github.com/THB-account/Julia4ML_GA/blob/1488fce07610da3bf5d159e77c945b94afef66fb/src/selection.jl#L90

**Comment by benbaute** [comment]
Thank you, for your feedback. We went ahead and resolved all issues mentioned.
