### ISSUE TITLE
Late Code Review 2

### ISSUE THREAD

**Issue by MaxHTu** [THB-account/Julia4ML_GA#40]
Late Code Review 2

Overall the package looks really nice especially the documentation. 

It would be nice to add more examples of different types of optimization problems to show the versatility of the package.
And optional some kinda of feedback after the algo finishes like this would be nice:

 * Status: success

 * Candidate solution
    Minimizer:  [0.010730015171837803, -0.01134228500190615, 0.008171974645544533]
    Minimum:    0.00031056182425975734
    Iterations: 66

**Comment by benbaute** [comment]
We used different types of optimization problems. Rosenbrock is an optimization of a real-valued function. Knapsack is a combinatorial problem based on a binary genome. TSP is finding the correct permutation. Sudoku is also a combinatorial problem similar to knapsack, but with an integer genome and not simply binary. This covers a wide range of optimization problems. We sadly do not have the time to add more.
The recommended feedback can be retrieved based on the trace object which can be optionally generated. 
Thanks for the feedback.
